[tool.poetry]
name = "mia"
version = "0.1.0"
description = "Mia is a smart detective with a knack for solving complex issues using dark humor."
authors = ["NLUX AI <contact@nlux.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
openai = "^0.10.2"
langchain-community = "^0.0.7"
langchain-core = "^0.1.4"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.5"

[tool.langserve]
export_module = "mia.chain"
export_attr = "chain"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
